<a href="https://colab.research.google.com/github/RTae/CPE212_Code_Summary/blob/master/CEP212_Summary_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Decase and Conquer

1) Decrease by a constant

- Insertion sort

In [0]:
def insertionSort(seq): 
  
    for i in range(1, len(seq)): 
        key = seq[i] 
        j = i-1
        while j >=0 and key < seq[j] : 
                seq[j+1] = seq[j] 
                j -= 1
        seq[j+1] = key

    return seq

In [0]:
seq = [23, 54, 0, 2, 5, 20, 49]
sorted = insertionSort(seq)

print(sorted)

[0, 2, 5, 20, 23, 49, 54]


- DFS (Depth First Search)

In [0]:
from collections import defaultdict 
  
class Graph: 
  
    def __init__(self,vertices): 
        self.graph = defaultdict(list) 
        self.V = vertices
  
    def addEdge(self, u, v): 
        self.graph[u].append(v) 
  
    def DFSUtil(self, v, visited): 

        visited[v] = True
        print(v, end = ' ') 

        for i in self.graph[v]: 
            if visited[i] == False: 
                self.DFSUtil(i, visited) 
  
    def DFS(self, v): 
        visited = [False] * (max(self.graph)+1) 
        self.DFSUtil(v, visited)

    def topologicalSortUtil(self,v,visited,stack): 
  
        visited[v] = True
  
        for i in self.graph[v]: 
            if visited[i] == False: 
                self.topologicalSortUtil(i,visited,stack) 
  
        stack.insert(0,v) 
  
    def topologicalSort(self): 
        visited = [False]*self.V 
        stack =[] 

        for i in range(self.V): 
            if visited[i] == False: 
                self.topologicalSortUtil(i,visited,stack) 
  
        print(stack) 

In [0]:
g = Graph(4) 
g.addEdge(0, 1) 
g.addEdge(0, 2) 
g.addEdge(1, 2) 
g.addEdge(2, 0) 
g.addEdge(2, 3) 
g.addEdge(3, 3) 
  
print("Following is DFS from (starting from vertex 2)") 
g.DFS(0)

Following is DFS from (starting from vertex 2)
0 1 2 3 

- Topological sort

In [0]:
g= Graph(5) 
g.addEdge(0, 2); 
g.addEdge(1, 2); 
g.addEdge(2, 3); 
g.addEdge(2, 4); 
g.addEdge(3, 4); 
  
print("Following is a Topological Sort of the given graph")
g.topologicalSort() 

Following is a Topological Sort of the given graph
[1, 0, 2, 3, 4]


- Generating combinatorial

>Permutation using Decrease by one

In [0]:
def permutation(lst): 
  
    if len(lst) == 0: 
        return [] 

    if len(lst) == 1: 
        return [lst] 

    l = [] 
  
    for i in range(len(lst)): 
       m = lst[i] 
  
       remLst = lst[:i] + lst[i+1:] 

       for p in permutation(remLst): 
           l.append([m] + p) 
    return l 

In [0]:
permutation(['A','B','C','D','E','F','G','I','J'])

[['A', 'B', 'C', 'D', 'E', 'F', 'G', 'I', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'J', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'I', 'G', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'I', 'J', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'J', 'G', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'J', 'I', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'F', 'I', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'F', 'J', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'I', 'F', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'I', 'J', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'J', 'F', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'J', 'I', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'F', 'G', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'F', 'J', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'G', 'F', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'G', 'J', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'J', 'F', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'J', 'G', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'J', 'F', 'G', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'J', 'F', 'I', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'J', 'G', 'F'

>Permutation using JohnsonTrotter

In [0]:
def jpermute(iterable):
    sequence = list(iterable)
    length = len(sequence)
    indices = range(1, length+1)

    # The list of directed integers: [-1, 1], [-1, 2], ...
    state = [[-1, idx] for idx in indices]

    # Add sentinels at the beginning and end
    state = [[-1, length+1]] + state + [[-1, length+1]]

    # The first permutation is the sequence itself
    yield sequence

    mobile_index = mobile_direction = direction = value = None
    while True:
        # 1. Find the highest mobile
        mobile = -1
        for idx in indices:
            direction, value = state[idx]
            if value > mobile and value > state[idx+direction][1]:
                # value is mobile and greater than the previous mobile
                mobile = value
                mobile_index = idx
                mobile_direction = direction
                if mobile == length:
                    # no point in continuing as mobile is as large as it can be.
                    break
        if mobile == -1:
            break

        # 2. Swap the mobile with the element it 'sees'
        sees = mobile_index + mobile_direction
        # ... first update the state
        state[mobile_index], state[sees] = state[sees], state[mobile_index]
        # ... then update the sequence
        sequence[mobile_index-1], sequence[sees-1] = sequence[sees-1], sequence[mobile_index-1]

        # 3. Switch the direction of elements greater than mobile
        if mobile < length:
            for idx in indices:
                if state[idx][1] > mobile:
                    state[idx][0] = -state[idx][0]

        yield sequence

In [0]:
permutation = jpermute("ABC")
for p in permutation:
    print(p)

['A', 'B', 'C']
['A', 'C', 'B']
['C', 'A', 'B']
['C', 'B', 'A']
['B', 'C', 'A']
['B', 'A', 'C']


2) Decrease by a constant factor

- Binary Search

In [0]:
def binary_search(seq,item):
	first = 0
	last = len(seq)-1
	found = False
	while( first<=last and not found):
		mid = (first + last)//2
		if seq[mid] == item :
			found = True
		else:
			if item < seq[mid]:
				last = mid - 1
			else:
				first = mid + 1	
	return found

In [0]:
print(binary_search([1,2,6,5,2], 6))
print(binary_search([4,2,3,6,8], 1))

True
False


3) Variable size decrease

- QuickSelect

In [0]:
def partition(arr, l, r): 
      
    x = arr[r] 
    i = l 
    for j in range(l, r): 
          
        if arr[j] <= x: 
            arr[i], arr[j] = arr[j], arr[i] 
            i += 1
              
    arr[i], arr[r] = arr[r], arr[i] 
    return i 
  
def kthSmallest(arr, l, r, k): 
  
    if (k > 0 and k <= r - l + 1): 
        index = partition(arr, l, r) 
        if (index - l == k - 1): 
            return arr[index] 
        if (index - l > k - 1): 
            return kthSmallest(arr, l, index - 1, k) 
  
        return kthSmallest(arr, index + 1, r, k - index + l - 1) 
    return INT_MAX 

In [0]:
arr = [ 7, 10, 4, 3, 20, 15 ] 
n = len(arr) 
k = 3
print("K-th smallest element is ", end = "") 
print(kthSmallest(arr, 0, n - 1, k)) 

K-th smallest element is 7


# Divide and Conquer

- Merge sort

In [0]:
def mergeSort(seq):
  if len(seq) > 1:
    mid = len(seq) // 2
    left = seq[:mid]
    right = seq[mid:]

    mergeSort(left)
    mergeSort(right)

    i = 0 # left
    j = 0 # right
    k = 0 # Iterator

    while i < len(left) and j < len(right):
      if left[i] < right[j]:
        seq[k] = left[i]
        i += 1
      else:
        seq[k] = right[j]
        j += 1
      k += 1

    while i < len(left):
      seq[k] = left[i]
      i += 1
      k += 1

    while j < len(right):
      seq[k]=right[j]
      j += 1
      k += 1

    return seq

In [0]:
# Input list 
a = [12, 11, 13, 5, 6, 7] 
  
sorted = mergeSort(a) 
  
print("Sorted array is : ") 
print(sorted)

Sorted array is : 
[5, 6, 7, 11, 12, 13]


- Lumuto Partition

In [0]:
def Lomuto(seq):
    l = 0
    p = seq[l]
    s = l

    for i in range(l+1, len(seq)):
        if seq[i] < p:
            s += 1
            seq[s], seq[i] = seq[i], seq[s]

    seq[l],seq[s] = seq[s],seq[l]

    return s, seq

In [0]:
x1 = [5 , 3 , 1 , 9 , 8 , 2 , 4 , 7 ]

In [0]:
key,seq = Lomuto(x1)
print('Index : '+str(key)+', Value : '+str(seq[key]))
print(seq)

Index : 4, Value : 5
[4, 3, 1, 2, 5, 9, 8, 7]


- Hoare Partition

In [0]:
def Hoare(A,l,r):
    p,i,j = A[l],l+1,r-1
    
    while i < j :
        while A[i] <= p:
            i += 1
            if i >= len(A)-1: 
                i = len(A) -1
                break
        while A[j] > p:
            j -= 1
        A[i],A[j] = A[j],A[i]
    A[i],A[j] = A[j],A[i]
    A[l],A[j] = A[j],A[l]
    return j

In [0]:
x1 = [5 , 3 , 1 , 9 , 8 , 2 , 4 , 7 ]

In [0]:
Hoare(x1,0,len(x1))

4

- Quick sort

In [0]:
def quickSort(A,l,r):
    if l < r-1:
        s = Hoare(A,l,r)
        quickSort(A,l,s)
        quickSort(A,s+1,r)

    return A

In [0]:
x2 = [5 , 3 , 1 , 9 , 8 , 2 , 4 , 7 ]

In [0]:
quickSort(x2,0,len(x2))

[1, 2, 4, 3, 5, 7, 8, 9]

- Strassen's Matrix Multiplication

In [0]:
import numpy as np 
  
def split(matrix): 
    row, col = matrix.shape 
    row2, col2 = row//2, col//2
    return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:] 
  
def strassen(x, y): 
  
    # Base case when size of matrices is 1x1 
    if len(x) == 1: 
        return x * y 
  
    # Splitting the matrices into quadrants. This will be done recursively 
    # untill the base case is reached. 
    a, b, c, d = split(x) 
    e, f, g, h = split(y) 
  
    # Computing the 7 products, recursively (p1, p2...p7) 
    m1 = strassen(a, f - h)   
    m2 = strassen(a + b, h)         
    m3 = strassen(c + d, e)         
    m4 = strassen(d, g - e)         
    m5 = strassen(a + d, e + h)         
    m6 = strassen(b - d, g + h)   
    m7 = strassen(a - c, e + f)   
  
    # Computing the values of the 4 quadrants of the final matrix c 
    c11 = m5 + m4 - m2 + m6   
    c12 = m1 + m2            
    c21 = m3 + m4             
    c22 = m1 + m5 - m3 - m7   
  
    # Combining the 4 quadrants into a single matrix by stacking horizontally and vertically. 
    c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))  
  
    return c 

In [0]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])

In [0]:
strassen(x,y)

array([[ 7, 10],
       [15, 22]])

- Closest pair

In [0]:
def find_closest_brute_force(array):
    
    result = {}
    result["p1"] = array[0]
    result["p2"] = array[1]
    result["distance"] = np.sqrt((array[0][0]-array[1][0])**2+(array[0][1]-array[1][1])**2)
    
    for i in range(len(array)-1):
        for j in range(i+1, len(array)):
            distance = np.sqrt((array[i][0]-array[j][0])**2+(array[i][1]-array[j][1])**2)
            if distance < result["distance"]:
                result["p1"] = array[i]
                result["p2"] = array[j]
                result["distance"] = distance
    return result

def merge_sort(array, coordinate=0):
    
    length = len(array)
    if length == 1:
        return array
    if length == 2:
        if array[0][coordinate] > array[1][coordinate]:
            return np.array([array[1], array[0]])
        else:
            return array
    
    elif length > 2:
        array_l = array[:length//2]
        array_r = array[length//2:]
        array_l_sorted = merge_sort(array_l, coordinate)
        array_r_sorted = merge_sort(array_r, coordinate)
        
        l_length = len(array_l)
        r_length = len(array_r)
        l = 0
        r = 0
        
        sorted_list = []
        
        for i in range(length):
            if r == r_length:
                sorted_list.append(array_l_sorted[l])
                l += 1
            elif l == l_length:
                sorted_list.append(array_r_sorted[r])
                r += 1             
                
            elif array_l_sorted[l][coordinate] > array_r_sorted[r][coordinate]:
                sorted_list.append(array_r_sorted[r])
                r += 1
                
            elif array_l_sorted[l][coordinate] < array_r_sorted[r][coordinate]:
                sorted_list.append(array_l_sorted[l])
                l += 1
        
        return np.array(sorted_list)

def find_closest_nest(array):
    X = merge_sort(array, 0)
    length = len(X)
    if length < 4:
      return find_closest_brute_force(array)
    
    else:
        array_l = X[:length//2]
        array_r = X[length//2:]
        dict_l = find_closest_nest(array_l)
        dict_r = find_closest_nest(array_r)
                    
        if dict_l["distance"] > dict_r["distance"]:
            dict_both = dict_r
        else:
            dict_both = dict_l
          
        Y_list = []
        for i in range(length):
            if X[length//2-1][0]-dict_both["distance"] < array[i][0] < X[length//2-1][0]+dict_both["distance"]:
                Y_list.append(array[i])
        Y = merge_sort(np.array(Y_list), 1)
      
        
        if len(Y) == 1:
            dict_final = dict_both
        elif len(Y) < 8:
            dict_y = find_closest_brute_force(Y)
            if dict_both["distance"] > dict_y["distance"]:
                dict_final = dict_y
            else:
                dict_final = dict_both            
        else:
            for i in range(len(Y)-7):
                dict_y = find_closest_brute_force(Y[i:i+7])        
                
                if dict_both["distance"] > dict_y["distance"]:
                    dict_final = dict_y
                else:
                    dict_final = dict_both
    
        return dict_final

In [0]:
point = np.array([[2, 3], [12, 30], [40, 50], [5, 1], [12, 10], [3, 4]])

In [0]:
find_closest_nest(point)

{'distance': 1.4142135623730951, 'p1': array([2, 3]), 'p2': array([3, 4])}

# Transform and Conquer

- Instance Simplification

> PresortUniqueElement

In [0]:
import time

def PresortUniqueElement(seq):
  quickSort(seq,0,len(seq))

  for i in range(0,len(seq)-1):
    if seq[i] == seq[i+1]:
      return True
    else:
      return False

def UniqueElement(seq):
  for i in range(len(seq)-1):
    for j in range(i+1,n):
      if seq[i] == seq[j]:
        return True
  return True

In [0]:
x1 = [1, 5, 2,1,3]


In [0]:
start1 = time.time()
PresortUniqueElement(x1)
end1 = time.time()

elp1 = end1-start1

start2 = time.time()
UniqueElement(x1)
end2 = time.time()

elp2 = end2-start2

In [0]:
print(elp1,elp2)

4.1484832763671875e-05 2.47955322265625e-05


> PresortMode

In [0]:
def mode(seq):
  n = len(seq)
  quickSort(seq,0,n)

  i=0
  modefrequency = 0
  modevalue = 0

  while i<=n-1:
    runlength = 1
    runvalue = seq[i]
    while i+runlength<=n-1 and seq[i+runlength] == runvalue:
      runlength += 1
    if runlength > modefrequency:
      modefrequency = runlength
      modevalue = runvalue
    i+=runlength
  return modevalue

In [0]:
seq = [6, 3, 2, 9, 1, 3, 6, 6, 2, 3, 1, 3, 2, 6, 9, 3, 2, 1, 2, 3]

In [0]:
mode(seq)

3

> LU Decomposition


In [0]:
import numpy as np 

def luDecomposition(mat): 
  
  n = len(mat)

  lower = [[0 for x in range(n)] for y in range(n)]
  upper = [[0 for x in range(n)] for y in range(n)]
                  
  for i in range(n): 
    # U 
    for k in range(i, n):  
      sum = 0; 
      for j in range(i): 
        sum += (lower[i][j] * upper[j][k]); 
      upper[i][k] = mat[i][k] - sum; 
  
    # L 
    for k in range(i, n): 
      if (i == k): 
        lower[i][i] = 1;
      else: 
        sum = 0; 
        for j in range(i): 
          sum += (lower[k][j] * upper[j][i]); 
        lower[k][i] = int((mat[k][i] - sum) /upper[i][i]); 
  
  print("Lower Triangular\t\tUpper Triangular"); 
  
  for i in range(n): 
          
    # Lower 
    for j in range(n): 
      print(lower[i][j], end = "\t");  
    print("", end = "\t"); 
  
    # Upper 
    for j in range(n): 
      print(upper[i][j], end = "\t"); 
    print(""); 
  

In [0]:
mat = [[1, -1, -2], 
       [-4, 2, 3], 
       [-4, -2, 3]]; 

In [0]:
luDecomposition(mat); 

Lower Triangular		Upper Triangular
1	0	0		1	-1	-2	
-4	1	0		0	-2	-5	
-4	3	1		0	0	10	


> AVL Tree (Only insertion) [Visulaztion](www.cs.usfca.edu/~galles/visualization/AVLtree.html)

In [0]:
class TreeNode(object): 
	def __init__(self, val): 
		self.val = val 
		self.left = None
		self.right = None
		self.height = 1

class AVL_Tree(object): 

	def insert(self, root, key): 
	
		if not root: 
			return TreeNode(key) 
		elif key < root.val: 
			root.left = self.insert(root.left, key) 
		else: 
			root.right = self.insert(root.right, key) 

		root.height = 1 + max(self.getHeight(root.left), self.getHeight(root.right)) 

		balance = self.getBalance(root) 

    # LL Case
		if balance > 1 and key < root.left.val: 
			return self.rightRotate(root) 

    # LR Case
		if balance < -1 and key > root.right.val: 
			return self.leftRotate(root) 

    # RR Case
		if balance > 1 and key > root.left.val: 
			root.left = self.leftRotate(root.left) 
			return self.rightRotate(root) 

    # RL Case
		if balance < -1 and key < root.right.val: 
			root.right = self.rightRotate(root.right) 
			return self.leftRotate(root) 

		return root 

	def leftRotate(self, z): 

		y = z.right 
		T2 = y.left 

		y.left = z 
		z.right = T2 

		z.height = 1 + max(self.getHeight(z.left), self.getHeight(z.right)) 
		y.height = 1 + max(self.getHeight(y.left), self.getHeight(y.right)) 

		return y 

	def rightRotate(self, z): 

		y = z.left 
		T3 = y.right 

		y.right = z 
		z.left = T3 

		# Update heights 
		z.height = 1 + max(self.getHeight(z.left), 
						self.getHeight(z.right)) 
		y.height = 1 + max(self.getHeight(y.left), 
						self.getHeight(y.right)) 

		return y 

	def getHeight(self, root): 
		if not root: 
			return 0

		return root.height 

	def getBalance(self, root): 
		if not root: 
			return 0

		return self.getHeight(root.left) - self.getHeight(root.right) 

	def preOrder(self, root): 

		if not root: 
			return

		print("{0} ".format(root.val), end="") 
		self.preOrder(root.left) 
		self.preOrder(root.right) 


In [0]:
myTree = AVL_Tree() 
root = None

root = myTree.insert(root, 10) 
root = myTree.insert(root, 20) 
root = myTree.insert(root, 30) 
root = myTree.insert(root, 40) 
root = myTree.insert(root, 50) 
root = myTree.insert(root, 25) 


"""The constructed AVL Tree would be 
		 30 
		/ \ 
	 20 40 
	/ \	 \ 
10 25   50

"""

print("Preorder traversal of the", "constructed AVL tree is") 
myTree.preOrder(root) 
print() 


Preorder traversal of the constructed AVL tree is
30 20 10 25 40 50 


- Representation Change

> 2-3 Trees [Animation](http://cs.armstrong.edu/liang/animation/web/24Tree.html)

In [0]:
import numpy as np
from bokeh.plotting import figure, show, output_notebook
from bokeh.io import push_notebook
from time import sleep

class Node:
    def __init__(self, value, left=None, right=None, red=False):
        self.value = value
        self.left = left
        self.right = right
        self.red = red

    @staticmethod
    def red(node):
        return node and node.red

    def rotate_left(self):
        if not Node.red(self.left) and Node.red(self.right):
            child = self.right
            self.right, child.left = child.left, self
            self.red, child.red = True, self.red
            return child
        else:
            return self

    def rotate_right(self):
        if Node.red(self.left) and Node.red(self.left.left):
            child = self.left
            self.left, child.right = child.right, self
            self.red, child.red = True, self.red
            return child
        else:
            return self
    
    def flip_colors(self):
        if Node.red(self.left) and Node.red(self.right):
            self.red, self.left.red, self.right.red = True, False, False

def insert(node, value, root=True):
    if not node:
        return Node(value, red=not root)
    
    # insert value
    if value == node.value:
        pass
    elif value < node.value:
        node.left = insert(node.left, value, root=False)
    else:
        node.right = insert(node.right, value, root=False)
    
    # update tree w.r.t invariants
    node = node.rotate_left()
    node = node.rotate_right()
    node.flip_colors()

    # keep root black
    if root:
        node.red = False

    return node

def draw(node, red, black, xlo=0, xhi=1, x=.5, y=0):
    if node:
        x_, y_ = (xlo + xhi) / 2, y - 1
        (red if node.red else black).append([x, y, x_, y_])
        draw(node.left, red, black, xlo, x_, x_, y_)
        draw(node.right, red, black, x_, xhi, x_, y_)

In [0]:
root = None
for i in range(20):
    root = insert(root, i)


output_notebook()

# get plot data
red, black = [], []
draw(root, red, black)

# plot
plot = figure(plot_height=400, plot_width=800)
plot.axis.visible = False
plot.grid.visible = False

red_segment = plot.segment(*zip(*red), color='#ff0000')
black_segment = plot.segment(*zip(*black), color='#000000')

handle = show(plot, notebook_handle=True)

for _ in range(100):
    for i in np.random.randint(0, 1000, 5):
        root = insert(root, i)

    red, black = [], []
    draw(root, red, black)

    x0, y0, x1, y1 = red and zip(*red) or [tuple()] * 4
    red_segment.data_source.data.update({
        'x0': x0, 'y0': y0, 'x1': x1, 'y1': y1
    })
    x0, y0, x1, y1 = black and zip(*black) or [tuple()] * 4
    black_segment.data_source.data.update({
        'x0': x0, 'y0': y0, 'x1': x1, 'y1': y1
    })

    push_notebook()
    sleep(.1)

- Problem reduction

> Find LCM

In [0]:
def GCD(x, y): 
  
   while(y): 
       x, y = y, x % y 
  
   return x 
  
    
def LCM(m,n):
    GCDV = GCD(m,n)
    
    return (m*n)/GCDV

In [0]:
a = 48
b = 60

print("LCM of "+str(a)+' and '+str(b)+' is '+str(LCM(a,b)))

LCM of 48 and 60 is 240.0


# Space and Time Trade-Offs

- Input enhancement

> Comparison counting sort

In [0]:
def CCS(seq): # aka Comparison Counting Sort
    #Initialize S and count 
    n = len(seq)
    S = [0]*n
    count = [0]*n
    
    print('----------------------------------------------------')
    print('Array A[0..'+str(n-1)+']\t | '+str(seq) + ' | ')
    print('Initially \t | '+str(count) + ' | ')
    print('----------------------------------------------------')

    #Count Sort
    for i in range(n):
        for j in range(i+1,n):
            if seq[i]<seq[j]:
                count[j] += 1
            else:
                count[i] += 1
        
        l = [ '' for k in count[0:i]]
        r = [ k for k in count[i:]]
        show = l+r
        if(i == n-1):
            print('Final State    \t| '+str(count) + ' | ')
        else:
            print('After pass i = '+str(i)+' | '+str(show) + ' | ')

    #Swap
    for i in range(n):
        S[count[i]] = seq[i]
        
    print('----------------------------------------------------')
    print('Array S[0..'+str(n-1)+']\t | '+str(S) + ' | SWAP')
    print('----------------------------------------------------')
    return S


In [0]:
A = [16,27,15,23,64,93,25,11]

In [0]:
CCS(A)

----------------------------------------------------
Array A[0..7]	 | [16, 27, 15, 23, 64, 93, 25, 11] | 
Initially 	 | [0, 0, 0, 0, 0, 0, 0, 0] | 
----------------------------------------------------
After pass i = 0 | [2, 1, 0, 1, 1, 1, 1, 0] | 
After pass i = 1 | ['', 5, 0, 1, 2, 2, 1, 0] | 
After pass i = 2 | ['', '', 1, 2, 3, 3, 2, 0] | 
After pass i = 3 | ['', '', '', 3, 4, 4, 3, 0] | 
After pass i = 4 | ['', '', '', '', 6, 5, 3, 0] | 
After pass i = 5 | ['', '', '', '', '', 7, 3, 0] | 
After pass i = 6 | ['', '', '', '', '', '', 4, 0] | 
Final State    	| [2, 5, 1, 3, 6, 7, 4, 0] | 
----------------------------------------------------
Array S[0..7]	 | [11, 15, 16, 23, 25, 27, 64, 93] | SWAP
----------------------------------------------------


[11, 15, 16, 23, 25, 27, 64, 93]

> Distribution counting sort

In [0]:
def DCS(A,l,u): #aka Distribution Counting Sort
    if l>u:
        print('Range error') # Check the range first
    
    else:
        #Initialize S and D 
        n = len(A)
        D = [0]*(u-l+1)
        S = [0]*n
        
        print('----------------------------------------------------')
        print('Array Value     \t| '+str([i for i in range(l,u+1)]))
        print('----------------------------------------------------')
        
        #Initialize Frequencies
        for i in range(n):
            D[A[i]-l]+=1
        
        print('Frequencies      \t| '+str(D))
        
        #reuse Distribution Value
        for j in range(1,u-l+1):
            D[j] = D[j-1] + D[j]
        
        print('Distribution Value  \t| '+str(D))
        print('----------------------------------------------------')

        #put on table
        print('\t   D[0..'+str(u-l)+']\t\tS[0..'+str(n-1)+']')
        for i in range(n-1,-1,-1):
            show = ['']*n
            j = A[i] - l
            show[D[j]-1] = A[i]
            S[D[j]-1] = A[i]
            print('A['+str(i)+'] = '+str(A[i]),end=' ')
            print(D,end='\t')
            print(show)
            D[j] -= 1
            
        print('----------------------------------------------------')
        print('Array S[0..'+str(n-1)+']\t\t '+str(S))
        print('----------------------------------------------------')
        return S
        

In [0]:
A = [1,4,2,1,3,2,1,3,2,3]    

In [0]:
DCS(A,min(A),max(A))

----------------------------------------------------
Array Value     	| [1, 2, 3, 4]
----------------------------------------------------
Frequencies      	| [3, 3, 3, 1]
Distribution Value  	| [3, 6, 9, 10]
----------------------------------------------------
	   D[0..3]		S[0..9]
A[9] = 3 [3, 6, 9, 10]	['', '', '', '', '', '', '', '', 3, '']
A[8] = 2 [3, 6, 8, 10]	['', '', '', '', '', 2, '', '', '', '']
A[7] = 3 [3, 5, 8, 10]	['', '', '', '', '', '', '', 3, '', '']
A[6] = 1 [3, 5, 7, 10]	['', '', 1, '', '', '', '', '', '', '']
A[5] = 2 [2, 5, 7, 10]	['', '', '', '', 2, '', '', '', '', '']
A[4] = 3 [2, 4, 7, 10]	['', '', '', '', '', '', 3, '', '', '']
A[3] = 1 [2, 4, 6, 10]	['', 1, '', '', '', '', '', '', '', '']
A[2] = 2 [1, 4, 6, 10]	['', '', '', 2, '', '', '', '', '', '']
A[1] = 4 [1, 3, 6, 10]	['', '', '', '', '', '', '', '', '', 4]
A[0] = 1 [1, 3, 6, 9]	[1, '', '', '', '', '', '', '', '', '']
----------------------------------------------------
Array S[0..9]		 [1, 1, 1, 2, 2, 2, 3

[1, 1, 1, 2, 2, 2, 3, 3, 3, 4]

> String Matching by Horspool's Algorithm

In [0]:
import string  

def ShiftTable(pattern):
     m = len(pattern)
     alphabet = [i for i in string.ascii_uppercase]
     alphabet.append('_')
     table ={alphabet[i]:i for i in range(len(alphabet))}
     for i in range(len(table)):
         table[alphabet[i]] = m
     for j in range(m - 1):
         table[pattern[j]] = m-1-j
     return table

In [0]:
def HorspoolMatching(P,T):
  table = ShiftTable(P)
  m = len(P)
  n = len(T)
  i = m -1
  while i <= n-1:
    k = 0
    while k <= m-1 and P[m-1-k] == T[i-k]:
      k += 1
    if k==m:
      return i-m+1
    else:
      i += table[T[i]]
  return -1

In [0]:
P = 'BARBER'
T = 'JIM_SAW_ME_IN_A_BARBER_SHOP'

In [0]:
key = HorspoolMatching(P,T)
print("pattern found at ",key)
print(T[key:key+len(P)])

pattern found at  16
BARBER


> String Matching by Boyer-Moore's Algorithm

In [0]:
def preprocess_strong_suffix(shift, bpos, pat, m): # good
  
    i = m 
    j = m + 1
    bpos[i] = j 
  
    while i > 0: 
        while j <= m and pat[i - 1] != pat[j - 1]: 
            if shift[j] == 0: 
                shift[j] = j - i 
  
            j = bpos[j] 
              
        i -= 1
        j -= 1
        bpos[i] = j 
  
def preprocess_case2(shift, bpos, pat, m):  #bad
    j = bpos[0] 
    for i in range(m + 1): 
          
        if shift[i] == 0: 
            shift[i] = j 

        if i == j: 
            j = bpos[j] 
  

def search(text, pat): 
  
    s = 0
    m = len(pat) 
    n = len(text) 
  
    bpos = [0] * (m + 1) 
  
    shift = [0] * (m + 1) 
  
    preprocess_strong_suffix(shift, bpos, pat, m) 
    preprocess_case2(shift, bpos, pat, m) 
    key = 0
    while s <= n - m: 
        j = m - 1
          
        while j >= 0 and pat[j] == text[s + j]: 
            j -= 1
              
        if j < 0: 
            key = s
            s += shift[0] 
        else: 
            s += shift[j + 1] 
    return key

In [0]:
P = 'BARBER'
T = 'JIM_SAW_ME_IN_A_BARBER_SHOP'
key = search(T, P)
print("pattern found at ",key)
print(T[key:key+len(P)])

pattern found at  16
BARBER


[B-Tree](https://www.cs.usfca.edu/~galles/visualization/BTree.html)

# Dynamic Programming

- Coin-Row problem

In [0]:
def CoinRow1D(C): # 1-D
  F = [i for i in range(len(C)+1)]
  F[0] = 0
  F[1] = C[0]
  for i in range(2,len(C)+1):
    F[i] = max(C[i-1]+F[i-2],F[i-1])
  return F

In [0]:
C = [5, 1, 2, 10, 6, 2]

In [0]:
CoinRow1D(C)

[0, 5, 5, 7, 15, 15, 17]

In [0]:
def CoinRow2D(C): # 2-D
  n = len(C)
  m = len(C[0])
  F = [[0]*(m) for i in range(n)]
  F[0][0] = C[0][0]
  for j in range(1,m):
    F[0][j] = F[0][j-1]+C[0][j]
  for i in range(1,n):
    F[i][0] = F[i-1][0]+C[i][0]
    for j in range(1,m):
      F[i][j] = max(F[i-1][j],F[i][j-1])+C[i][j]
  return F[n-1][m-1]

In [0]:
C = [[0, 0, 0, 0, 1, 0],[0, 1, 0, 1, 0, 0],[0, 0, 0, 1, 0, 1],[0, 0, 1, 0, 0, 1],[1, 0, 0, 0, 1, 0]]

In [0]:
CoinRow2D(C)

5

 - Knapsack problem

In [0]:
import numpy as np

def knapSack(C, wt, val):
   F = [[0]*(C + 1) for x in range(len(val) + 1)]
   for i in range(len(val) + 1):
    F[i][0] = max(val)
   for j in range(C + 1):
    F[0][j] = max(val)
   for i in range(1,len(val) + 1):
      for j in range(1,C + 1):
         if j-wt[i-1] >= 0:
            F[i][j] = max(F[i-1][j],val[i-1] + F[i-1][j-wt[i-1]])
         else:
            F[i][j] = F[i-1][j]
   return F

In [0]:
W = [2,1,3,2]
V = [-12,-10,-20,-15]
C = 5

In [0]:
knapSack(C, W, V)

[[-10, -10, -10, -10, -10, -10],
 [-10, -10, -10, -10, -10, -10],
 [-10, -10, -10, -10, -10, -10],
 [-10, -10, -10, -10, -10, -10],
 [-10, -10, -10, -10, -10, -10]]

In [0]:
def permutation(lst): 
  
    if len(lst) == 0: 
        return [] 

    if len(lst) == 1: 
        return [lst] 

    l = [] 
  
    for i in range(len(lst)): 
       m = lst[i] 
  
       remLst = lst[:i] + lst[i+1:] 

       for p in permutation(remLst): 
           l.append([m] + p) 
    return l 

In [0]:
permutation(['A','B','C','D','E','F','G','I','J'])

[['A', 'B', 'C', 'D', 'E', 'F', 'G', 'I', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'J', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'I', 'G', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'I', 'J', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'J', 'G', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'F', 'J', 'I', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'F', 'I', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'F', 'J', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'I', 'F', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'I', 'J', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'J', 'F', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'G', 'J', 'I', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'F', 'G', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'F', 'J', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'G', 'F', 'J'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'G', 'J', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'J', 'F', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'I', 'J', 'G', 'F'],
 ['A', 'B', 'C', 'D', 'E', 'J', 'F', 'G', 'I'],
 ['A', 'B', 'C', 'D', 'E', 'J', 'F', 'I', 'G'],
 ['A', 'B', 'C', 'D', 'E', 'J', 'G', 'F'

In [0]:
lst = ['C', 'B', 'D', 'E', 'G', 'E', 'J', 'F', 'I']
City = {
        'A':[3,80],
        'B':[4,85],
        'C':[5,100],
        'D':[2,45],
        'E':[3,75],
        'F':[1,25],
        'G':[6,148],
        'H':[8,205],
        'I':[1,24],
        'J':[7,200]
        }
day = 0
cost = 0

for i in lst:
  if 14 > day:
    day += City[i][0]
    cost += City[i][1]
    print(City[i][0],City[i][1])
print(day)
print(cost)

5 100
4 85
2 45
3 75
14
305


- Warshall's Algorithms

In [0]:
import numpy as np


class Warshall():
    
    def Warshall(self,A):
        
        n = len(A)+1
        R = np.array([[[ 0 ]*(n-1) for i in range(n-1) ]  for k in range(n)])
        R[0] = A
        

        for k in range(1,n):
            for i in range(len(A)):
                for j in range(len(A)):
                    R[k][i,j] = R[k-1][i,j] or (R[k-1][i,k-1] and R[k-1][k-1,j])
                    
        return R
    
    
    def showWarshall(self,A):
        log = self.Warshall(A)
        
        print('---------------------------')
        print('\tWarshall algorithm')
        print('---------------------------')
        
        for i in range(len(log)):
            c = 0
            for j in range(len(log[i])):
                if(c == 0):
                    print('R('+str(i)+')',end= '\t')
                    print(log[i][j])
                    c+=1
                else:
                    print('',end= '\t')
                    print(log[i][j])
            print('')
            
        print('---------------------------')
        print('\tFinal answer')
        print('---------------------------')
        print(log[len(A)])
        print('')
        print('')


In [0]:
W = Warshall()
A = np.array([[0,1,0,0],[0,0,0,1],[0,0,0,0],[1,0,1,0]])
W.showWarshall(A)

---------------------------
	Warshall algorithm
---------------------------
R(0)	[0 1 0 0]
	[0 0 0 1]
	[0 0 0 0]
	[1 0 1 0]

R(1)	[0 1 0 0]
	[0 0 0 1]
	[0 0 0 0]
	[1 1 1 0]

R(2)	[0 1 0 1]
	[0 0 0 1]
	[0 0 0 0]
	[1 1 1 1]

R(3)	[0 1 0 1]
	[0 0 0 1]
	[0 0 0 0]
	[1 1 1 1]

R(4)	[1 1 1 1]
	[1 1 1 1]
	[0 0 0 0]
	[1 1 1 1]

---------------------------
	Final answer
---------------------------
[[1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]]




- Floyd's Algorithms

In [0]:
import numpy as np


class Floyd():

    def Floyd(self,W):
        n = len(W)
        

        for k in range(n):
            for i in range(n):
                for j in range(n):
                    W[i,j] = min(W[i,j],W[i,k]+W[k,j])
                    
        return W
    
    def showFloyd(self,W):
        log = self.Floyd(W)
        
        print('---------------------------')
        print('\tFloyd algorithm')
        print('---------------------------')
        print('\tFinal answer')
        print('---------------------------')
        print(log)
        print('')
        print('')


In [0]:
inf = -np.NINF
A = np.array([[0, 3, inf, 2, 6],[5, 0, 4, 2, inf],[inf, inf, 0, 5, inf],[inf, inf, 1, 0, 4],[5, inf, inf, inf, 0]])
F = Floyd()
F.showFloyd(A)

---------------------------
	Floyd algorithm
---------------------------
	Final answer
---------------------------
[[ 0.  3.  3.  2.  6.]
 [ 5.  0.  3.  2.  6.]
 [14. 17.  0.  5.  9.]
 [ 9. 12.  1.  0.  4.]
 [ 5.  8.  8.  7.  0.]]




- Test

In [0]:

INF = 1000000

def MinimumCost(cost, n, W,weight): 

	val = list() 
	wt= list() 
	size = 0
	for i in range(n): 
		if (cost[i] != -1): 
			val.append(cost[i]) 
			wt.append(i+1) 
			size += 1

	n = size 
	min_cost = [[0 for i in range(W+1)] for j in range(n+1)] 

	for i in range(W+1): 
		min_cost[0][i] = INF 

	for i in range(1, n+1): 
		min_cost[i][0] = 0

	for i in range(1, n+1): 
		for j in range(1, W+1): 
			if (wt[i-1] > weight[j]): 
				min_cost[i][j] = min_cost[i-1][j] 

			else: 
				min_cost[i][j] = min(min_cost[i-1][j], min_cost[i][j-wt[i-1]] + val[i-1]) 

	if(min_cost[n][W] == INF): 
		return -1
	else: 
		return min_cost[n][W] 

# Driver program to run the test case 
cost = [1, 2, 3, 4, 5] 
weight = [0,2, 32, 4, 1, 2]
W = 5
n = len(cost) 

print(MinimumCost(cost, n, W,weight)) 

# This code is contributed by Soumen Ghosh. 


5


# Greedy Technique

- Minimum spanning tree

> Prim's algorithms

In [0]:
import numpy as np
  
class Graph(): 
  
    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
  
    def printMST(self, parent): 
        print( "Edge \tWeight")
        for i in range(1, self.V): 
            print (parent[i], "-", i, "\t", self.graph[i][ parent[i] ] )

    def minKey(self, key, mstSet): 
  
        min = np.inf 
  
        for v in range(self.V): 
            if key[v] < min and mstSet[v] == False: 
                min = key[v] 
                min_index = v 
  
        return min_index 
   
    def primMST(self): 
  
        key = [np.inf] * self.V 
        parent = [None] * self.V 
        key[0] = 0 
        mstSet = [False] * self.V 
  
        parent[0] = -1 
  
        for cout in range(self.V): 
  
            u = self.minKey(key, mstSet) 
            mstSet[u] = True
  
            for v in range(self.V): 
                if self.graph[u][v] > 0 and mstSet[v] == False and key[v] > self.graph[u][v]: 
                        key[v] = self.graph[u][v] 
                        parent[v] = u 
  
        self.printMST(parent) 
  

In [0]:
g = Graph(5) 
g.graph = [ [0, 2, 0, 6, 0], 
            [2, 0, 3, 8, 5], 
            [0, 3, 0, 0, 7], 
            [6, 8, 0, 0, 9], 
            [0, 5, 7, 9, 0]] 
  
g.primMST();

Edge 	Weight
0 - 1 	 2
1 - 2 	 3
0 - 3 	 6
1 - 4 	 5


> Kruskal algorithms

In [0]:
  
class Graph: 
  
    def __init__(self,vertices): 
        self.V= vertices 
        self.graph = []
          
    def addEdge(self,u,v,w): 
        self.graph.append([u,v,w]) 
  
    def find(self, parent, i): 
        if parent[i] == i: 
            return i 
        return self.find(parent, parent[i]) 

    def union(self, parent, rank, x, y): 
        xroot = self.find(parent, x) 
        yroot = self.find(parent, y) 
  
        if rank[xroot] < rank[yroot]: 
            parent[xroot] = yroot 
        elif rank[xroot] > rank[yroot]: 
            parent[yroot] = xroot 
  
        else : 
            parent[yroot] = xroot 
            rank[xroot] += 1
  
    def KruskalMST(self): 
  
        result =[] 
  
        i = 0 
        e = 0 

        self.graph =  sorted(self.graph,key=lambda item: item[2]) 
  
        parent = [] ; rank = [] 
  
        for node in range(self.V): 
            parent.append(node) 
            rank.append(0) 
      
        while e < self.V -1 : 

            u,v,w =  self.graph[i] 
            i = i + 1
            x = self.find(parent, u) 
            y = self.find(parent ,v) 

            if x != y: 
                e = e + 1     
                result.append([u,v,w]) 
                self.union(parent, rank, x, y)             
  
        print("Following are the edges in the constructed MST")
        for u,v,weight  in result: 
            print ("%d -- %d == %d" % (u,v,weight)) 

In [0]:
g = Graph(4) 
g.addEdge(0, 1, 10) 
g.addEdge(0, 2, 6) 
g.addEdge(0, 3, 5) 
g.addEdge(1, 3, 15) 
g.addEdge(2, 3, 4) 
  
g.KruskalMST() 

Following are the edges in the constructed MST
2 -- 3 == 4
0 -- 3 == 5
0 -- 1 == 10


> Dijkstra algorithms

In [0]:
from collections import deque, namedtuple
inf = float('inf')
Edge = namedtuple('Edge', 'start, end, cost')


def make_edge(start, end, cost=1):
  return Edge(start, end, cost)


class Graph:
    def __init__(self, edges):
        wrong_edges = [i for i in edges if len(i) not in [2, 3]]
        if wrong_edges:
            raise ValueError('Wrong edges data: {}'.format(wrong_edges))

        self.edges = [make_edge(*edge) for edge in edges]

    @property
    def vertices(self):
        return set(
            sum(
                ([edge.start, edge.end] for edge in self.edges), []
            )
        )

    def get_node_pairs(self, n1, n2, both_ends=True):
        if both_ends:
            node_pairs = [[n1, n2], [n2, n1]]
        else:
            node_pairs = [[n1, n2]]
        return node_pairs

    def add_edge(self, n1, n2, cost=1, both_ends=True):
        node_pairs = self.get_node_pairs(n1, n2, both_ends)
        for edge in self.edges:
            if [edge.start, edge.end] in node_pairs:
                return ValueError('Edge {} {} already exists'.format(n1, n2))

        self.edges.append(Edge(start=n1, end=n2, cost=cost))
        if both_ends:
            self.edges.append(Edge(start=n2, end=n1, cost=cost))

    @property
    def neighbours(self):
        neighbours = {vertex: set() for vertex in self.vertices}
        for edge in self.edges:
            neighbours[edge.start].add((edge.end, edge.cost))

        return neighbours

    def dijkstra(self, source, dest):
        assert source in self.vertices, 'Such source node doesn\'t exist'
        distances = {vertex: inf for vertex in self.vertices}
        previous_vertices = { vertex: None for vertex in self.vertices}
        distances[source] = 0
        vertices = self.vertices.copy()

        while vertices:
            current_vertex = min(
                vertices, key=lambda vertex: distances[vertex])
            vertices.remove(current_vertex)
            if distances[current_vertex] == inf:
                break
            for neighbour, cost in self.neighbours[current_vertex]:
                alternative_route = distances[current_vertex] + cost
                if alternative_route < distances[neighbour]:
                    distances[neighbour] = alternative_route
                    previous_vertices[neighbour] = current_vertex

        path, current_vertex = deque(), dest
        while previous_vertices[current_vertex] is not None:
            path.appendleft(current_vertex)
            current_vertex = previous_vertices[current_vertex]
        if path:
            path.appendleft(current_vertex)
        return path


In [0]:
graph = Graph([
    ("a", "b", 7),  ("a", "c", 9),  ("a", "f", 14), ("b", "c", 10),
    ("b", "d", 15), ("c", "d", 11), ("c", "f", 2),  ("d", "e", 6),
    ("e", "f", 9)])

print(graph.dijkstra("a", "e"))

deque(['a', 'c', 'd', 'e'])


> HuffmanCodeTree algorithms

In [0]:
class NodeTree(object):

    def __init__(self, left=None, right=None):
        self.left = left
        self.right = right

    def children(self):
        return (self.left, self.right)

    def nodes(self):
        return (self.left, self.right)

    def __str__(self):
        return '%s_%s' % (self.left, self.right)


def huffmanCodeTree(node, left=True, binString=''):
    if type(node) is str:
        return {node: binString}
    (l, r) = node.children()
    d = dict()
    d.update(huffmanCodeTree(l, True, binString + '0'))
    d.update(huffmanCodeTree(r, False, binString + '1'))
    return d


In [0]:
string = 'AABBAACCDDC'
freq = {}

for c in string:
    if c in freq:
        freq[c] += 1
    else:
        freq[c] = 1

freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)

nodes = freq

while len(nodes) > 1:
    (key1, c1) = nodes[-1]
    (key2, c2) = nodes[-2]
    nodes = nodes[:-2]
    node = NodeTree(key1, key2)
    nodes.append((node, c1 + c2))

    nodes = sorted(nodes, key=lambda x: x[1], reverse=True)

huffmanCode = huffmanCodeTree(nodes[0][0])

print(' Char | Huffman code ')
print('----------------------')
for (char, frequency) in freq:
    print(' %-4r |%12s' % (char, huffmanCode[char]))

 Char | Huffman code 
----------------------
 'A'  |           0
 'C'  |          10
 'B'  |         111
 'D'  |         110


In [0]:
huffmanDeCode = {huffmanCode[i]:i for i in huffmanCode}
print(x)

{'0': 'A', '10': 'C', '110': 'D', '111': 'B'}


In [0]:
testString = ''

for i in string:
    testString = testString + huffmanCode[i]

In [0]:
testString

'0011111100101011011010'

In [0]:
def huffmanDecode (dictionary, text):
    res = ""
    while text:
        for k in dictionary:
            if text.startswith(k):
                res += dictionary[k]
                text = text[len(k):]
    return res

In [0]:
x = huffmanDecode(huffmanDeCode,testString)

In [0]:
x

'AABBAACCDDC'

- Test

In [0]:
class ItemValue: 
      
    """Item Value DataClass"""
    def __init__(self, wt, val, ind): 
        self.wt = wt 
        self.val = val 
        self.ind = ind 
        self.cost = val // wt 
  
    def __lt__(self, other): 
        return self.cost < other.cost 
  
# Greedy Approach 
class FractionalKnapSack: 
      
    """Time Complexity O(n log n)"""
    @staticmethod
    def getMaxValue(wt, val, capacity): 
          
        """function to get maximum value """
        iVal = [] 
        for i in range(len(wt)): 
            iVal.append(ItemValue(wt[i], val[i], i)) 
  
        # sorting items by value 
        iVal.sort() 
        totalValue = 0
        for i in iVal: 
            curWt = int(i.wt) 
            curVal = int(i.val) 
            if capacity - curWt >= 0: 
                capacity -= curWt 
                totalValue += curVal 
                print(curWt,curVal)
                print(i.cost)
                print(totalValue)
        print(capacity)
        return totalValue 


In [0]:
W = [3,4,5,2,3,1,6,8,1,7]
V = [80,85,100,45,75,25,148,205,24,200]
C = 14
  
maxValue = FractionalKnapSack.getMaxValue(W, V, C) 
print("Maximum value in Knapsack =", maxValue)

5 100
20
100
4 85
21
185
2 45
22
230
1 24
24
254
1 25
25
279
1
Maximum value in Knapsack = 279


# Lterative Improvement

- Stable Marriage

In [0]:
def break_engagement(person):
    breakingWith = is_engaged_to(person)
    for m in males:
        if m["name"] == person:
            if m["engaged_to"] != "":
                m["engaged_to"] = ""
                m["is_free"] = True
                print("{} is breaking with {}.".format(person, breakingWith))

    for f in females:
        if f["name"] == person:
            if f["engaged_to"] != "":
                f["engaged_to"] = ""
                m["is_free"] = True
                print("{} is breaking with {}.".format(person, breakingWith))


def is_engaged_to(person):
    for m in males:
        if m["name"] == person:
            return m["engaged_to"]

    for f in females:
        if f["name"] == person:
            return f["engaged_to"]

    return False


def is_engaged(person):
    for m in males:
        if m["name"] == person:
            if m["engaged_to"] != "":
                return True

    for f in females:
        if f["name"] == person:
            if f["engaged_to"] != "":
                return True

    return False


def who_do_you_love_more(person, candidate1, candidate2):
    for m in males:
        if m["name"] == person:
            for x in range(0, len(males)):
                if candidate1 == m["preferences"][x]:
                    return candidate1
                if candidate2 == m["preferences"][x]:
                    return candidate2

    for f in females:
        if f["name"] == person:
            for x in range(0, len(males)):
                if candidate1 == f["preferences"][x]:
                    return candidate1
                if candidate2 == f["preferences"][x]:
                    return candidate2


def engage(dramaKing, dramaQueen):
    for m in males:
        if m["name"] == dramaKing:
            m["engaged_to"] = dramaQueen
            m["is_free"] = False

    for f in females:
        if f["name"] == dramaQueen:
            f["engaged_to"] = dramaKing
            f["is_free"] = False


def get_name_from_ranking(dramaKing, rank):
    for m in males:
        if m["name"] == dramaKing:
            return m["preferences"][rank]


def main():
    while (True):
        numberOfPairs = len(males)
        good = 1
        for m in males:
            dramaKing = m["name"]
            if (m["is_free"] == False) and (len(m["proposed_to"]) != numberOfPairs):
                good += 1
                if good == numberOfPairs:
                    print("\n\n\nSuccess!")
                    return

            for x in range(0, numberOfPairs):
                if not is_engaged(dramaKing):
                    if x not in m["proposed_to"]:
                        m["proposed_to"].append(x)

                        woman = get_name_from_ranking(dramaKing, x)

                        if is_engaged(woman):
                            currentManOfTheEngaged = is_engaged_to(woman)

                            betterLover = who_do_you_love_more(
                                woman, currentManOfTheEngaged, dramaKing)

                            engage(betterLover, woman)

                            if betterLover != currentManOfTheEngaged:
                                break_engagement(currentManOfTheEngaged)
                        else:
                            engage(dramaKing, woman)


def happyend():
    print("Resolution:\n")
    for m in males:
        dramaKing = m["name"]
        dramaQueen = m["engaged_to"]

        print("{} <---> {}".format(dramaKing, dramaQueen))

In [0]:
males = [
    {
        "name": "Bob",
        "is_free": True,
        "gender": "male",
        "preferences": ["Lea", "Ann", "Sue"],
        "engaged_to": "",
        "proposed_to":[],
    },
    {
        "name": "Jim",
        "is_free": True,
        "gender": "male",
        "preferences": ["Lea", "Sue", "Ann"],
        "engaged_to": "",
        "proposed_to":[],
    },
    {
        "name": "Tom",
        "is_free": True,
        "gender": "male",
        "preferences": ["Sue", "Lea", "Ann"],
        "engaged_to": "",
        "proposed_to":[],
    }
]

females = [
    {
        "name": "Ann",
        "is_free": True,
        "gender": "female",
        "preferences": ["Jim", "Tom", "Bob"],
        "engaged_to": "",
        "proposed_to":[],
    },
    {
        "name": "Lea",
        "is_free": True,
        "gender": "female",
        "preferences": ["Tom", "Bob", "Jim"],
        "engaged_to": "",
        "proposed_to":[],
    },
    {
        "name": "Sue",
        "is_free": True,
        "gender": "female",
        "preferences": ["Jim", "Tom", "Bob"],
        "engaged_to": "",
        "proposed_to":[],
    },
]


main()
happyend()

Bob is breaking with Lea.



Success!
Resolution:

Bob <---> Ann
Jim <---> Sue
Tom <---> Lea
